name: Build and push Docker images

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1
  DOCKER_REPOSITORY: ssamoilenko/hsa-25-ec2

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        # Don't use this kind of tagging in production ;)
        run: |
          docker build ./service-one --tag $DOCKER_REPOSITORY:one
          docker build ./service-two --tag $DOCKER_REPOSITORY:two
          docker push $DOCKER_REPOSITORY:one
          docker push $DOCKER_REPOSITORY:two
